### ISSUE TITLE
Lines between labels and slices

### ISSUE THREAD

**Issue by ekmartin** [FormidableLabs/victory-pie#106]
Would be nice if there was an option to enable indicator lines between the labels and the chart. Makes it a lot easier to see what labels belong to what slice.

Example (taken from react-d3):
![image](https://cloud.githubusercontent.com/assets/3536982/16856094/acf8725c-4a18-11e6-8a1b-855c222067c1.png)

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#363
