### ISSUE TITLE
Animation doesn't tween between states when the number of data points changes

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-pie#19]
Instead of animating smoothly between states, when the number of data points is different between two states, the transition just snaps to the next state.

**Comment by sburns** [comment]
Possibly related, when transitioning to 0 data points, it doesn't transition at all and continues to render using the pre-transition data.

**Comment by boygirl** [comment]
Closing in favor of the more general animation issue https://github.com/FormidableLabs/victory-core/issues/13
