### ISSUE TITLE
audit tags / npm versions

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-pie#23]
make sure there is a tag for every npm version

**Comment by boygirl** [comment]
npm versions:
`[ '0.0.1', '0.0.2', '0.1.0', '0.1.1' ]`

tags:
`v0.0.2, v0.1.0, v0.1.1`

missing tags: `v0.0.1`

**Comment by cpb** [comment]
Found https://github.com/FormidableLabs/victory-pie/tree/v0.0.1 by installing victory-pie@v0.0.1 and checking package.json for `gitHead`
